# Generated by Django 5.2.5 on 2025-10-21 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='schedule',
            unique_together={('course', 'semester')},
        ),
    ]
